import torch
from sbi_bax.calculate import entropy_at_x
from typing import Callable, List, Tuple
from sbi.inference.posteriors.base_posterior import NeuralPosterior


def posterior_terms(
    outer_thetas: torch.Tensor,
    alg_path_gen: Callable[[torch.Tensor], torch.Tensor],
    n_mc_theta: int,
    posterior: NeuralPosterior,
) -> Tuple[List[torch.Tensor], List[torch.Tensor]]:
    """
    Precompute terms for the second term of the Expected Information Gain (EIG).

    Args:
        outer_thetas (torch.Tensor): Outer thetas sampled from the posterior.
        alg_path_gen (callable): Function that generates the algorithm execution path given theta.
        n_mc_theta (int): Number of Monte Carlo samples for theta.
        full_ea_posterior (Posterior): Posterior object to condition and sample from.
        noise_sim (float): Noise level for the simulator.

    Returns:
        Tuple[List[torch.Tensor], List[torch.Tensor]]:
            - c_outer_thetas: List of sampled outer thetas conditioned on x.
            - c_inner_thetas: List of sampled inner thetas conditioned on x.
    """

    def sample_and_condition(theta):
        """Helper function to sample x, condition the posterior, and sample thetas."""
        # Define the algorithm execution path by simulating the data
        algo_path = alg_path_gen(theta)
        # Condition the posterior on the generated samples
        posterior.set_default_x(algo_path)
        # Sample compatible thetas with silenced output
        c_outer = posterior.sample((n_mc_theta,), show_progress_bars=False)
        c_inner = posterior.sample((n_mc_theta,), show_progress_bars=False)
        return c_outer, c_inner

    # Use a list comprehension to process all outer thetas
    results = [sample_and_condition(theta) for theta in outer_thetas]
    # Unpack the results into separate lists
    c_outer_thetas, c_inner_thetas = zip(*results)

    return list(c_outer_thetas), list(c_inner_thetas)


def eig_at_x(
    x: torch.Tensor,
    outer_thetas: torch.Tensor,
    inner_thetas: torch.Tensor,
    outer_c_thetas: List[torch.Tensor],
    inner_c_thetas: List[torch.Tensor],
    simulator: Callable[[torch.Tensor, torch.Tensor, float], torch.Tensor],
    density_function: Callable[
        [torch.Tensor, torch.Tensor, torch.Tensor], torch.Tensor
    ],
    n_mc_sim: int = 1000,
    noise_sim: bool = False,
    return_entropies: bool = False,
) -> float:
    """
    Calculate the expected information gain (EIG) for a given input x.

    Parameters
    ----------
    x : torch.Tensor
        Input data for which to calculate the EIG.
    outer_thetas : torch.Tensor
        Thetas for the outer loop.
    inner_thetas : torch.Tensor
        Thetas for the inner loop.
    outer_c_thetas : list of torch.Tensor
        List of thetas compatible with samples drawn from each outer theta.
        Generated by first sampling from p(theta | D_t), then sampling from p(e_A | theta),
        then sampling from p(theta | e_A).
        These values should be passed as lists because they are sampled from distributions
        that are independent of x, so they can be reused across multiple calls to this function.
    inner_c_thetas : list of torch.Tensor
        List of thetas compatible with samples drawn from each outer theta.
        Drawn from same distribution as the outer_c_thetas.
    simulator : callable
        Function to simulate data based on theta.
    density_function : callable
        Function to compute the density.
    n_mc_sim : int, optional
        Number of Monte Carlo simulations, by default 1000.
    noise_sim : bool, optional
        Whether to add noise in simulations, by default False.

    Returns
    -------
    eig_x : float
        The expected information gain at x.
    """
    # Get an MC estimate for H(y_x | D_t).
    h_yx_dt = entropy_at_x(
        x,
        outer_thetas,
        inner_thetas,
        simulator,
        density_function,
        n_mc_sim,
        noise_sim,
    )

    # This is an MC estimate for the second term in the EIG.
    e_h_ea = (
        torch.tensor(
            [
                entropy_at_x(
                    x,
                    outer_c_thetas[kk],
                    inner_c_thetas[kk],
                    simulator,
                    density_function,
                    n_mc_sim,
                    noise_sim,
                )
                for kk in range(len(outer_thetas))
            ]
        )
        .mean()
        .item()
    )
    # Calculate the expected information gain (EIG).
    eig_x = h_yx_dt - e_h_ea
    if return_entropies:
        # Return the entropies used to calculate the EIG.
        return eig_x, h_yx_dt, e_h_ea
    else:
        # Return only the EIG.
        return eig_x
