---
# Functional experiment configuration for source finding
defaults:
  - dataset_encoder: transformer
  - acquisition: nle_exact
  - hydra: default
  - sbi: default
  - design_net: default
  - _self_
# Experiment settings
seed: 100
output_dir: results
exp_name: pharma_first
data:
  _target_: sbi_bax.data.pharmacokinetic.PharmacoKineticData
  n_points: 1000  # Number of candidate measurement points
  seed: ${seed}  # For indexing into iDAD thetas
  hyperspherical: false
  simulator:
    _target_: sbi_bax.simulators.pharmacokinetic.Pharmacokinetic
# Interpolated variables
full_path: ${output_dir}/${exp_name}
# Measurement parameters
measurement:
  max_measure: 5
  initial_measure: 1
  from_scratch: false
# Evaluation parameters
eval:
  n_contrast: 1e7
